/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.cliv.vilp

import com.cliv_git.vilp.*
import kotlin.io.path.Path

fun Array<String>.parseArguments(): MutableList<String> {
    val arguments = this.toMutableList()
    return if (arguments.isEmpty()) {
        arguments.add("")
        arguments
    } else arguments
}

fun main(args: Array<String>) {
    println(Path(".").resolve(".git"))
    val arguments = args.parseArguments()
    when (arguments[0]) {
        "git" -> processGitCommands(arguments)
        else -> println("No command found!")
    }
}
