/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.cliv.vilp

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun main() {
    val a = App()
    a.greeting = "A"
    println(App().greeting)
}
